routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@getIndex')->name('home');
Route::resource('pages', 'PagesController');
Route::resource('posts', 'PostsController');
Route::resource('categories', 'CategoriesController');

Auth::routes();

resources/views/pages/contact.blade.php
@extends('main')

@section('title', '| Contact')

@section('content')
    <div class="blog-header">
        <h1 class="blog-title">Contact</h1>
        <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
    </div>

    <div class="row">
        <div class="col-sm-8 blog-main">
           
            <div class="blog-post">
            <h2 class="blog-post-title">Another blog post</h2>
                <p class="blog-post-meta">December 23, 2013 by <a href="#">Jacob</a></p>

                <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
                <blockquote>
                    <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                </blockquote>
                
                <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
                <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
            </div><!-- /.blog-post -->
            
            ...

            <nav>
                <ul class="pager">
                    <li><a href="#">Previous</a></li>
                    <li><a href="#">Next</a></li>
                </ul>
            </nav>
            
        </div><!-- /.blog-main -->
        
        <!--Sidebar-->
        @include('partials._sidebar')

    </div><!-- /.row -->
@endsection

resources/views/pages/frontpage.blade.php
@extends('main')

@section('title', '| Front Page')

@section('content')
    <div class="blog-header">
        <h1 class="blog-title">The Bootstrap Blog</h1>
        <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
    </div>
    
    <div class="row">
        <div class="col-sm-8 blog-main">
            
            @if( $posts->count() )
                @foreach( $posts as $post )
                    
                    <div class="blog-post">
                        <h2 class="blog-post-title">
                            <a href="/?p={{ $post->id }}">{{ $post->post_title }}</a>
                        </h2>
                        <p class="blog-post-meta">{{ date('M j, Y', strtotime( $post->created_at )) }} by <a href="#">{{ $post->author_ID }}</a></p>
                    
                        <div class="blog-content">
                            {!! nl2br( $post->post_content ) !!}
                        </div>
                    </div>

                @endforeach
            @else

                <p>No post added yet!</p>

            @endif

            {{-- Display pagination only if more than the required pagination --}}
            @if( $posts->total() > 6 )
                <nav>
                    <ul class="pager">
                        @if( $posts->firstItem() > 1 )
                            <li><a href="{{ $posts->previousPageUrl() }}">Previous</a></li>
                        @endif
                        
                        @if( $posts->lastItem() < $posts->total() )
                            <li><a href="{{ $posts->nextPageUrl() }}">Next</a></li>
                        @endif
                    </ul>
                </nav>
            @endif

        </div><!-- /.blog-main -->
        
        <!--Sidebar-->
        @include('partials._sidebar')

    </div><!-- /.row -->
@endsection

resources/views/pages/index.blade.php
@extends('main')

@section('title', '| Pages')

@section('content')

    <div class="container">
        
        {{-- Check if current user is logged-in or a guest --}}
        @if (Auth::guest())
            
            <p class="mt-5">Cheatn?, please <a href="/login/">login</a> to continue.</p>
            
        @else
            
            <div class="blog-header">
                <h1 class="blog-title">Pages <a class="btn btn-sm btn-primary" href="{{ route('pages.create') }}">Add New</a></h1>
            </div>
            
            <div class="row">
                <div class="col-md-12">
                    
                    <table class="table">
                        <tr>
                            <th>Title</th>
                            <th>Author</th>
                            <th>Content</th>
                            <th>Date</th>
                            <th>&nbsp;</th>
                        </tr>
                        <tr>
                            {{-- Blade if and else --}}
                            @if( $pages->count() )
                                {{-- Blade foreach --}}
                                @foreach( $pages as $page )
                                    <tr>
                                        <td>
                                            <strong>
                                                <a href="{{ route('pages.edit', $page->id) }}">
                                                    {{ $page->post_title }}
                                                </a>
                                            </strong>
                                        </td>
                                        <td>{{ $page->author_ID }}</td>
                                        <td>
                                            @if ( strlen( $page->post_content ) > 60 )
                                                {{ substr( $page->post_content, 0, 60 ) }} ...
                                            @else
                                                {{ $page->post_content }}
                                            @endif
                                        </td>
                                        <td>Published {{ date( 'j/m/Y', strtotime( $page->created_at ) ) }}</td>
                                        <td>
                                            <form class="d-inline" action="{{ route('pages.destroy', $page->id) }}" method="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}

                                                <input type="submit" value="Delete" class="btn btn-sm btn-danger" />
                                            </form>

                                            <a class="btn btn-sm btn-info" href="{{ route('pages.edit', $page->id) }}">Edit</a>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                
                                <tr>
                                    <td colspan="5">No page has been added yet!</td>
                                </tr>

                            @endif
                        </tr>
                    </table>

                    {{ $pages->links() }}

                </div>
            </div>

        @endif

    </div>
    
@endsection

resources/views/pages/page.blade.php
@extends('main')

@section('title')
    | {{ $page->post_title }}
@endsection

@section('content')
    
    <div class="blog-header">
        <h1 class="blog-title">{{ $page->post_title }}</h1>
        <p>{{ date('M j, Y', strtotime( $page->created_at )) }} <a href="{{ route('posts.edit', $page->id) }}">{Edit}</a></p>
    </div>
    
    <div class="row">
        <div class="col-sm-8 blog-main">
            
            <div class="blog-content">
                {!! nl2br( $page->post_content ) !!}
            </div><!-- /.blog-post -->
            
        </div><!-- /.blog-main -->
        
        <!--Sidebar-->
        @include('partials._sidebar')
    </div><!-- /.row -->

@endsection

resources/views/pages/services.blade.php
@extends('main')

@section('title', '| Services')

@section('content')
    <div class="blog-header">
        <h1 class="blog-title">Services</h1>
    </div>
    
    <div class="row">
        <div class="col-sm-8 blog-main">
            
            <div class="blog-content">
                <p>This blog post shows a few different types of content that's supported and styled with Bootstrap. Basic typography, images, and code are all supported.</p>
                ...
            </div><!-- /.blog-post -->
            
        </div><!-- /.blog-main -->
        
        <!--Sidebar-->
        @include('partials._sidebar')

    </div><!-- /.row -->
@endsection

resources/views/pages/show.blade.php
@extends('main')

@section('title', '| Page')

@section('content')
		
	<div class="container">
		
		{{-- Check if current user is logged-in or a guest --}}
		@if (Auth::guest())
			
			<p class="mt-5">Cheatn?, please <a href="/login/">login</a> to continue.</p>
			
		@else
		
			<div class="blog-header">
		        <h1 class="blog-title">{{ $page->post_title }}</h1>
		        <p>{{ date('M j, Y', strtotime( $page->created_at )) }} <a href="{{ route('pages.edit', $page->id) }}">{Edit}</a></p>
		    </div>
			
			<div class="row">
				<div class="col-sm-12 blog-main">

					<div class="blog-content">
						{{-- Inserts HTML line breaks before all newlines in a string --}}
						{!! nl2br( $page->post_content ) !!}
					</div>

				</div>
			</div>
			
		@endif

	</div>
	
@endsection

resources/views/pages/showcase.blade.php
@extends('main')

@section('title', '| Show Case')

@section('content')
    <div class="blog-header">
        <h1 class="blog-title">Show Case</h1>
    </div>
    
    <div class="row">
        <div class="col-sm-8 blog-main">
            
            <div class="blog-content">
                <p>This blog post shows a few different types of content that's supported and styled with Bootstrap. Basic typography, images, and code are all supported.</p>
                ...
            </div><!-- /.blog-post -->
            
        </div><!-- /.blog-main -->
        
        <!--Sidebar-->
        @include('partials._sidebar')

    </div><!-- /.row -->
@endsection

resources/views/pages/single.blade.php
@extends('main')

@section('title')
    | {{ $post->post_title }}
@endsection

@section('content')
   
    <div class="blog-header">
        <h1 class="blog-title">{{ $post->post_title }}</h1>
        <p>{{ $post->category_ID }} / {{ date('M j, Y', strtotime( $post->created_at )) }} <a href="{{ route('posts.edit', $post->id) }}">{Edit}</a></p>
    </div>
    
    <div class="row">
        <div class="col-sm-8 blog-main">
            
            <div class="blog-content">
                {!! nl2br( $post->post_content ) !!}
            </div><!-- /.blog-post -->
            
            <section class="mt-5" id="comment">
                <p>Comment goes here!</p>
            </section>

        </div><!-- /.blog-main -->
        
        <!--Sidebar-->
        @include('partials._sidebar')
    </div><!-- /.row -->

@endsection